"use client";

import type { MetricSnapshot, Insight, Anomaly } from "@/lib/types";

interface ExecutiveSummaryProps {
  projectName: string;
  metrics: MetricSnapshot[];
  insights: Insight[];
  anomalies: Anomaly[];
  healthScore: number;
  periodStart: string;
  periodEnd: string;
}

function generateSummaryLines(
  metrics: MetricSnapshot[],
  insights: Insight[],
  anomalies: Anomaly[],
  healthScore: number,
): string[] {
  const lines: string[] = [];

  // Health
  if (healthScore >= 80) {
    lines.push(`Overall subscription health is strong with a score of ${healthScore}/100.`);
  } else if (healthScore >= 50) {
    lines.push(`Subscription health is fair at ${healthScore}/100 — some areas need attention.`);
  } else {
    lines.push(`Subscription health needs attention at ${healthScore}/100. Several metrics are below benchmarks.`);
  }

  // Anomalies
  const criticalAnomalies = anomalies.filter((a) => a.severity === "critical");
  if (criticalAnomalies.length > 0) {
    lines.push(`${criticalAnomalies.length} critical anomaly${criticalAnomalies.length > 1 ? "ies" : ""} detected requiring investigation.`);
  }

  // Trends
  const upMetrics = metrics.filter((m) => m.trend === "up");
  const downMetrics = metrics.filter((m) => m.trend === "down");
  if (upMetrics.length > 0) {
    lines.push(`${upMetrics.length} metric${upMetrics.length > 1 ? "s" : ""} trending positively: ${upMetrics.map((m) => m.name).join(", ")}.`);
  }
  if (downMetrics.length > 0) {
    lines.push(`${downMetrics.length} metric${downMetrics.length > 1 ? "s" : ""} trending down: ${downMetrics.map((m) => m.name).join(", ")}.`);
  }

  return lines;
}

function generateRecommendations(insights: Insight[]): string[] {
  return insights
    .filter((i) => i.recommendation)
    .slice(0, 5)
    .map((i) => i.recommendation!);
}

export default function ExecutiveSummary({
  projectName,
  metrics,
  insights,
  anomalies,
  healthScore,
  periodStart,
  periodEnd,
}: ExecutiveSummaryProps) {
  const summaryLines = generateSummaryLines(metrics, insights, anomalies, healthScore);
  const recommendations = generateRecommendations(insights);

  const startStr = new Date(periodStart).toLocaleDateString("en-US", { month: "long", year: "numeric" });
  const endStr = new Date(periodEnd).toLocaleDateString("en-US", { month: "long", year: "numeric" });

  // Generate markdown report for download
  const generateMarkdown = () => {
    let md = `# RC Copilot Analysis Report — ${projectName}\n\n`;
    md += `**Period:** ${startStr} – ${endStr}\n\n`;
    md += `**Health Score:** ${healthScore}/100\n\n`;
    md += `## Executive Summary\n\n`;
    summaryLines.forEach((line) => (md += `- ${line}\n`));
    md += `\n## Key Metrics\n\n`;
    md += `| Metric | Current | Previous | Change | Trend |\n`;
    md += `|--------|---------|----------|--------|-------|\n`;
    metrics.forEach((m) => {
      const unit = m.unit === "$" || m.unit === "USD" ? "$" : m.unit === "%" ? "%" : "";
      const cur = unit === "$" ? `$${m.current.toLocaleString()}` : unit === "%" ? `${m.current.toFixed(1)}%` : m.current.toLocaleString();
      const prev = unit === "$" ? `$${m.previous.toLocaleString()}` : unit === "%" ? `${m.previous.toFixed(1)}%` : m.previous.toLocaleString();
      md += `| ${m.name} | ${cur} | ${prev} | ${m.changePercent > 0 ? "+" : ""}${m.changePercent.toFixed(1)}% | ${m.trend} |\n`;
    });
    md += `\n## Recommendations\n\n`;
    recommendations.forEach((r, i) => (md += `${i + 1}. ${r}\n`));
    md += `\n## Anomalies\n\n`;
    anomalies.forEach((a) => {
      md += `- **${a.label}** (${new Date(a.date).toLocaleDateString("en-US")}): ${a.deviation > 0 ? "+" : ""}${a.deviation}σ — ${a.severity}\n`;
    });
    md += `\n---\n*Generated by RC Copilot • Built by Caio Vicentino for RevenueCat*\n`;
    return md;
  };

  const handleDownload = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `rc-copilot-report-${new Date().toISOString().split("T")[0]}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-800 border border-slate-700 rounded-xl p-6">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-lg font-semibold text-slate-100">Executive Summary</h3>
          <p className="text-sm text-slate-400">{startStr} – {endStr}</p>
        </div>
        <button
          onClick={handleDownload}
          className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-slate-200 text-sm font-medium rounded-lg transition-colors cursor-pointer"
        >
          Download Report
        </button>
      </div>

      <div className="space-y-3 mb-6">
        {summaryLines.map((line, i) => (
          <p key={i} className="text-sm text-slate-300 leading-relaxed">
            {line}
          </p>
        ))}
      </div>

      {recommendations.length > 0 && (
        <div>
          <h4 className="text-sm font-medium text-slate-400 uppercase tracking-wider mb-3">Key Recommendations</h4>
          <ul className="space-y-2">
            {recommendations.map((rec, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
                <span className="text-emerald-400 mt-0.5 shrink-0">&#9654;</span>
                {rec}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
